config/routes.rb
require 'sequenceserver'
require "#{Rails.root}/lib/links.rb"  
Rails.application.routes.draw do
  
  root 'wellcome#default'
  get 'wellcome/search_gene'

  get 'download' => 'download#default'
  get 'cite' =>  'wellcome#cite'
 
  resources :genes  do
    collection do
      get 'autocomplete'
      get 'heatmap'
      post 'forward'
      get 'forward'
      post 'share' 
      get 'set_studies_session'     
      get 'show'
      get 'examples'
    end
  end
  
  get 'expression_values/gene' => 'expression_values#gene'
  get 'expression_values/transcript' => 'expression_values#transcript'
  get 'expression_values/genes' => 'expression_values#genes'

  get 'expression/:gene_set/gene/:name',
    to: 'expression_values#gene_values',
    defaults: {format: 'json'},
    constraints: {name: /.*/, gene_set: /.*/}
  get 'expression/:gene_set/transcript/:name', 
    to: 'expression_values#transcript_values',
    defaults: {format: 'json'},
    constraints: {name: /.*/, gene_set: /.*/}
  

  resources :gene_sets  do
    collection do
      get 'set_gene_set_session'     
    end
  end
  
  begin
    config_ss = {}
    if Rails.application.config.respond_to?(:sequenceserver_config)
      config_file = Rails.application.config.sequenceserver_config 
      config_ss[:config_file]  =  config_file if Dir.exist? config_file
    end
    SequenceServer.init config_ss
    mount SequenceServer, :at => "sequenceserver"
  rescue Exception => e
    Logger.new(STDOUT).info "Unable to start sequenceserver: " + e.to_s
  end
  
  
end

app/models/study.rb
class Study < ActiveRecord::Base 
	belongs_to :species
	has_many :experiment_groups

	def to_factor
		ret = Factor.new
		ret.name = self.accession
		ret.description = self.title
		ret.order = self.order
		ret.selected = self.selected
		ret
	end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]

  # GET /studies
  # GET /studies.json
  def index
    @studies = Study.all
  end

  # GET /studies/1
  # GET /studies/1.json
  def show
  end

  # GET /studies/new
  def new
    @study = Study.new
  end

  # GET /studies/1/edit
  def edit
    @study = Study.find(params[:id])
    #Rails.logger.level = 0
    @species = @study.species
    @all_species = Species.all
    #logger.info @all_species
  end

  # POST /studies
  # POST /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: 'Study was successfully created.' }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: 'Study was successfully updated.' }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url, notice: 'Study was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_params
      par = params.require(:study).permit(:species, :title, :manuscript)
      par["species"] = Species.find(par["species"])
      par
    end
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_form.html.erb
<%= form_for(@study) do |f| %>
  <% if @study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study.errors.count, "error") %> prohibited this study from being saved:</h2>

      <ul>
      <% @study.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :species %><br>
    <%= f.select :species, @all_species.map{ |p| [p.to_s, p.id]}, :selected => @study.species.id  %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :manuscript %><br>
    <%= f.text_field :manuscript %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studies/edit.html.erb
<h1>Editing Study</h1>

<%= render 'form' %>

<%= link_to 'Show', @study %> |
<%= link_to 'Back', studies_path %>

app/views/studies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Studies</h1>

<table>
  <thead>
    <tr>
      <th>Species</th>
      <th>Title</th>
      <th>Manuscript</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @studies.each do |study| %>
      <tr>
        <td><%= study.species %></td>
        <td><%= study.title %></td>
        <td><%= study.manuscript %></td>
        <td><%= link_to 'Show', study %></td>
        <td><%= link_to 'Edit', edit_study_path(study) %></td>
        <td><%= link_to 'Destroy', study, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study', new_study_path %>

app/views/studies/new.html.erb
<h1>New Study</h1>

<%= render 'form' %>

<%= link_to 'Back', studies_path %>

app/views/studies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Species:</strong>
  <%= @study.species %>
</p>

<p>
  <strong>Title:</strong>
  <%= @study.title %>
</p>

<p>
  <strong>Manuscript:</strong>
  <%= @study.manuscript %>
</p>

<%= link_to 'Edit', edit_study_path(@study) %> |
<%= link_to 'Back', studies_path %>