config/routes.rb
require 'sequenceserver'
require "#{Rails.root}/lib/links.rb"  
Rails.application.routes.draw do
  
  root 'wellcome#default'
  get 'wellcome/search_gene'

  get 'download' => 'download#default'
  get 'cite' =>  'wellcome#cite'
 
  resources :genes  do
    collection do
      get 'autocomplete'
      get 'heatmap'
      post 'forward'
      get 'forward'
      post 'share' 
      get 'set_studies_session'     
      get 'show'
      get 'examples'
    end
  end
  
  get 'expression_values/gene' => 'expression_values#gene'
  get 'expression_values/transcript' => 'expression_values#transcript'
  get 'expression_values/genes' => 'expression_values#genes'

  get 'expression/:gene_set/gene/:name',
    to: 'expression_values#gene_values',
    defaults: {format: 'json'},
    constraints: {name: /.*/, gene_set: /.*/}
  get 'expression/:gene_set/transcript/:name', 
    to: 'expression_values#transcript_values',
    defaults: {format: 'json'},
    constraints: {name: /.*/, gene_set: /.*/}
  

  resources :gene_sets  do
    collection do
      get 'set_gene_set_session'     
    end
  end
  
  begin
    config_ss = {}
    if Rails.application.config.respond_to?(:sequenceserver_config)
      config_file = Rails.application.config.sequenceserver_config 
      config_ss[:config_file]  =  config_file if Dir.exist? config_file
    end
    SequenceServer.init config_ss
    mount SequenceServer, :at => "sequenceserver"
  rescue Exception => e
    Logger.new(STDOUT).info "Unable to start sequenceserver: " + e.to_s
  end
  
  
end

app/models/gene.rb
class Gene < ActiveRecord::Base
	belongs_to :gene_set
	has_many :expression_values;
	has_many :type_of_value , through: :expression_values
	has_many :meta_experiment , through: :expression_values
	has_and_belongs_to_many :ortholog_groups
	def add_field(text)
		arr = text.split(":", 2)
		#puts arr.inspect
		arr[0] = "possition" if arr[0] == "scaffold" or arr[0] == "chromosome"
		arr.unshift("description") if arr.size == 1

		#puts arr.inspect
		self.send(arr[0]+'=',arr[1])
	end

	def to_s
		name
	end

	def full_gene_name
		"#{gene_set.name}:#{gene}"
	end

	def chromosome
		self.name[chrom_pos]
	end

	def genome 
		self.name[chrom_pos + 1]
	end

	def is_traes? #Following the IWGSC convention
		self.name.starts_with? "Traes"
	end

	def is_triae? #Following TGAC convention
		self.name.starts_with? "TRIAE_CS42"
	end

	def chrom_pos
		number_poistions = name.scan(/[[:digit:]]/)
		return name.index(number_poistions[2] )if self.is_triae?	
		return name.index(number_poistions[0])
	end

end

app/controllers/genes_controller.rb
class GenesController < ApplicationController

  require 'digest'  

  before_action :set_gene, only: [:show, :edit, :update, :destroy]

  def examples
    @gene_set = GeneSet.find(session[:gene_set_id])
    examples = GenesHelper.get_example_genes(@gene_set)
    respond_to do |format|      
      format.json { 
        render json: examples
      }
    end
  end

  def getGeneIds(genes)
    gs = Set.new
    gene_set = GeneSet.find(session[:gene_set_id])    
    old_search_by = false
    genes.each do |g|  
      next if g.size == 0
      gene, search_by = GenesHelper.findGeneName(g, gene_set)
      l_name = search_by == "gene" ?  gene.gene : gene.name
      gs << l_name
      old_search_by = search_by unless old_search_by
      raise "Unable to compare a mix of genes and transcripts." unless search_by == old_search_by
    end
    return gs.to_a
  end

  def getGeneset
    @gene_set = GeneSet.find(params[:gene_set_selector]) if params[:gene_set_selector]
    @gene_set = GeneSet.find(params[:gene_set_selector_main]) if params[:gene_set_selector_main]
    @gene_set = GeneSet.find_by(:name => params[:gene_set]) if params[:gene_set]    
    return @gene_set
  end

  def validateURILength(gene_set, genes)
    arguments = {gene_set: gene_set, genes: genes}.to_query
    uri = "#{request.base_url}/genes/heatmap/#{arguments}"
    return false if WEBrick::HTTPRequest::MAX_URI_LENGTH < uri.length
    return true
  end

  def manageNumOfGenes(gene_set, genes)
    managed_genes = []
    removed_genes = []
    genes_arr = genes.split(",")
    genes_query = {}

   # arguments = {gene_set: gene_set, genes: genes}.to_query
    uri_base = "#{request.base_url}/genes/heatmap/"
    allowed_arg_length = WEBrick::HTTPRequest::MAX_URI_LENGTH - uri_base.length

    genes_arr.each do |gene|
      genes_query = {genes: managed_genes}.to_query
      if (genes_query.length + gene.length) > allowed_arg_length
        removed_genes.push(gene)
      else
        managed_genes.push(gene)
      end
    end

    return managed_genes.join(','), removed_genes.length
  end

  def forwardHeatmap
    @gene_set = getGeneset
    genes = params[:genes_heatmap].split(/[,|\s]+/).map { |e| e.strip }
    raise "Please select less than 500 genes" if genes.size > 500
    ids = getGeneIds(genes)
    raise "Please select some genes for the heatmap" if ids.size == 0
    genes = ids.join(',')

    genes,removed_genes  = manageNumOfGenes(@gene_set.name, genes) unless validateURILength(@gene_set.name, genes)

    flash.notice = "Removed last #{removed_genes} genes due to limited URL length" if removed_genes

    redirect_to action: "heatmap",
                genes: genes,
                gene_set: @gene_set.name
  end

  def forwardCommon
    gene_name = nil
    gene_name = params[:gene]
    gene_name = params[:query] if params[:query]
    gene_name.gsub!(/\s+/, '')
    @gene_set = getGeneset
    session[:heatmap] = false
    @gene, @search_by = GenesHelper.findGeneName gene_name, @gene_set 
    @search_by = params[:search_by] if ["gene", "transcript"].include? params[:search_by]
    session[:name] = @search_by == "gene" ? @gene.gene : @gene.name 
    session[:search_by] = @search_by
    session[:gene_set_id] = @gene_set.id
  end

  def forwardSearch
    forwardCommon    
    redirect_to  action: "show", 
      search_by: @search_by, 
      name: session[:name], 
      gene_set: @gene_set.name
  end

  def forwardCompare
    forwardCommon
    compare = params[:compare].gsub(/\s+/, '')
    @compare, @search_by_compare = GenesHelper.findGeneName compare, @gene_set
    raise "Can't compare gene vs transcript" unless @search_by == @search_by_compare
    redirect_to  action: "show", 
      search_by: @search_by, 
      name: session[:name], 
      gene_set: @gene_set.name,
      compare:  params[:compare] 
  end

  # GET /genes
  # GET /genes.json
  def forward
    session[:studies] = params[:studies] if  params[:studies]     
    begin
      case params[:submit] 
      when "Heatmap"
        forwardHeatmap 
      when "Search"
        forwardSearch
      when "Compare"
        forwardCompare
      else
        raise "Unknow redirect: #{params[:submit]}"
      end
    rescue Exception => e
      flash[:error] = e.to_s
      #puts "ERROR: #{e.inspect}"
      #puts e.backtrace
      redirect_back fallback_location: request.base_url.to_s 
    end
  end

  def autocomplete
    gene_set_id = session[:gene_set_id] 
    @genes = Gene.order(:name).where("name LIKE ? and gene_set_id = ?", "%#{params[:term]}%", gene_set_id).limit(20)

    respond_to do |format|
      format.html
      format.json { 
        render json: [@genes.map(&:gene).uniq, @genes.map(&:transcript) ].flatten
      }
    end
  end

  def heatmap    
    genes = ""
    genes = session[:genes] if  session[:genes] 
    genes = params[:genes]  if  params[:genes]
    session[:studies] = params[:studies] if  params[:studies] 
    studies = session[:studies]
    session[:genes] = params[:genes] if params[:genes]
    session[:heatmap] = true
    session[:gene_set_id] = getGeneset.id if params[:gene_set]

    # If parameters passed contain settings (it's a shared link)
    studies = set_shared_settings if params[:settings]
    # Since session is set for genes if it's a shared link the following line needs to be called
    genes = session[:genes] if  session[:genes]

    genes_arr = genes.split(',')

    gene = {
      name: genes_arr
    }

    # Generate links to other websites (limit of 70 genes to generate a link to KnetMiner)
    if genes_arr.length <= 70
      @link = Link.all
      site_name = nil
      @link.each do |url_element|
        site_name = url_element.site_name
        gene[site_name] = url_element.url.gsub("<gene>", genes) if site_name == "knetminer"
      end
    end

    @gene = OpenStruct.new(gene)

    @args = {studies: studies,  }.to_query
    respond_to do |format|
      format.html { render :heatmap }
    end
  end

  # GET /genes/1
  # GET /genes/1.json
  def show 
    #Use TRIAE_CS42_2BL_TGACv1_130848_AA0418720 as it has multiple transcripts
    studies = session[:studies] if session[:studies]
    compare = ""
    #alert = ""

    #search_by = params[:search_by]
    #search_by.capitalize! if search_by
    gene = {
      name: params[:name],
      gene: params[:name], 
      search_by:  params[:search_by],
      gene_set: params[:gene_set]
    }
    if params[:compare]
      compare = {
        name: params[:compare]
      }
    else
      compare = {
        name: ""
      }
    end
    
    # If parameters passed contain settings (it's a shared link)
    studies = set_shared_settings if params[:settings]
    
    studies = [] if studies == nil

    # Select all studies if not studies are in session
    if studies.empty?
      Study.where("active").order('`order` ASC').each do |study|
        studies.push(study.accession)
      end
    end

    # Generate links to other websites
    # This needs to be dynamic! 
    @link = Link.all
    site_name = nil
    @link.each do |url_element|
      site_name = url_element.site_name
      if site_name == "knetminer" and params[:search_by] == "transcript"
        gene[site_name] = url_element.url.gsub("<gene>", Gene.find_by(:transcript=>params[:name]).gene)
        compare[site_name] = url_element.url.gsub("<gene>", Gene.find_by(:transcript=>params[:compare]).gene) unless compare[:name] == ""
      else
        gene[site_name] = url_element.url.gsub("<gene>", gene[:gene])
        compare[site_name] = url_element.url.gsub("<gene>", compare[:name]) unless compare[:name] == ""
      end
    end

    @gene = OpenStruct.new(gene)
    @compare = OpenStruct.new(compare)

    @args = {studies: studies,name: @gene.name ,compare: @compare.name, gene_set: params[:gene_set]  }.to_query  

    #studies.each { |e|  @studies += "studies[]=#{e}\&" }`
  end  

  def share 
    # Hash the settings sent by the clinet's request
    sha1 = Digest::SHA1.new
    if session[:heatmap]
      hash_salt = params[:settings] + session[:genes]
    else
      hash_salt = params[:settings]
    end
    sha1 << hash_salt
    hashed_settings = sha1.hexdigest

    # Get the gene set & gene
    gene_set = GeneSet.find(session[:gene_set_id])          
    gene_name = params[:gene]       
    session[:gene] = gene_name
    @gene, @search_by = GenesHelper.findGeneName gene_name, gene_set unless session[:heatmap]    
    
    # Preparing the DB record
    gene_name = @gene.name if gene_name    
    db_record = {:gene_set => gene_set.name, :name => gene_name, :search_by => @search_by, :settings => params[:settings], :hash => hashed_settings}
    db_record[:genes] = session[:genes] if session[:genes] and session[:heatmap]

    # Store the settings in the DB  
    @client = MongodbHelper.getConnection unless @client
    @client[:share].insert_one(db_record) if @client[:share].find({'hash' => hashed_settings}).count == 0
    
    #Generate the sharable URL and pass it to the client
    response = create_sharable_link gene_set.name, hashed_settings
    
    respond_to do |format|
      format.json { render json: {"value" => response}}      
    end
    
  end

  def set_studies_session
    session[:studies] = JSON.parse params[:studies]    
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gene
      @gene = Gene.find(params[:id]) if numeric? params[:id]
      @gene = Gene.find_by(:name=>params[:gene]) unless @gene
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gene_params
      params.require(:gene).permit(:name,:studies, :cdna, :possition, :gene, :transcript)
    end

    def numeric?(string)
      # `!!` converts parsed number to `true`
      !!Kernel.Float(string) 
    rescue TypeError, ArgumentError
      false
    end
    
    def create_sharable_link gene_set_name, hashed_settings
      if session[:heatmap]

app/helpers/genes_helper.rb
module GenesHelper
	
	def self.get_random_genes(gene_set, count: 50)
		random_genes = Gene.where(gene_set_id: gene_set.id).order("RAND()").limit(count)
		example = {}
		example[:search]  = random_genes.first
		example[:compare] = random_genes.last
		example[:heatmap] = random_genes.map { |e| e.gene }
		example
	end
	
	def self.get_example_genes(gene_set)
		example = {}
		example[:search]  = SampleGene.where(gene_set_id: gene_set.id, kind:'search')
		example[:compare] = SampleGene.where(gene_set_id: gene_set.id, kind:'compare')
		example[:heatmap] = SampleGene.where(gene_set_id: gene_set.id, kind:'heatmap')
		if example[:search].size == 0
			return get_random_genes(gene_set)  
		end
		#This only allows one gene for each.
		example[:search]  = Gene.where(id: example[:search] .first.gene_id).first
		example[:compare] = Gene.where(id: example[:compare].first.gene_id).first
		example[:heatmap] = example[:heatmap].map { |e| e.gene.gene  }
		example
	end
	
	def self.find(gene)
		raise "Mongo is deprecated"
		@client = MongodbHelper.getConnection unless @client 
		gene_mongo = @client[:genes].find({:_id => gene.id}).first
		gene_mongo
	end
	def self.saveGene(gene)
		raise "Mongo is deprecated"
		@client = MongodbHelper.getConnection unless @client 
		gene.save!
		doc = { :name => gene.name } 
		@client[:genes].update_one( 
			{ :_id => gene.id }, 
			{ '$set' => doc}, 
			upsert:true
		)
		
	end
	
	def self.findTranscripts(gene_name, gene_set)
		transcripts = Array.new
		Gene.where("gene = :gene_name AND gene_set_id = :gene_set", 
			{
				gene_name: gene_name, 
				gene_set: gene_set.id
			}
		).each do |t|
			transcripts << t
		end
		transcripts
	end
	
	
	def self.saveValues(gene, type, values)		
		@client = MongodbHelper.getConnection unless @client 
		@client[:genes].update({ 
			:_id => gene.id }, 
			'$set' => { type => values 
			}
		)
	end
	
	def self.load_gene_hash(gene_set)
		genes = Hash.new
		Gene.find_by_sql("SELECT * FROM genes where gene_set_id='#{gene_set.id}'").each do |g|  
			genes[g.name] = g
		end
		genes
	end
	
	def self.findGeneName(gene_name, gene_set)
		gene = Gene.find_by(:name=>gene_name, :gene_set_id=>gene_set.id)      
		gene = Gene.find_by(:gene=>gene_name, :gene_set_id=>gene_set.id) unless  gene     
		raise "\n\n\nGene not found: #{gene_name} for #{gene_set.name}\n\n\n" unless gene
		return [gene,  gene_name == gene.gene ? "gene": "transcript" ]  
	end

	def self.load_ensembl_genes(gene_set, filename)
		ActiveRecord::Base.transaction do
			gene_set = GeneSet.find_or_create_by(:name => gene_set)
			#puts gene_set.inspect
			Bio::FlatFile.open(Bio::FastaFormat, filename) do |ff|
			  ff.each do |entry|
				arr = entry.definition.split(/ description:"(.*?)" *| /)
				g = Gene.new
				g.gene_set = gene_set
				g.name = arr.shift
				arr.each { |e| g.add_field(e) }
				g.save!
				#GenesHelper.saveGene(g)
			  end
			end
		  end
	end

	def self.load_pangenome_cdna(gene_set, filename)
		ActiveRecord::Base.transaction do
			gene_set = GeneSet.find_or_create_by(:name => :gene_set)
			stream = Zlib::GzipReader.open(:filename) 
			i=0
			Bio::FlatFile.open(Bio::FastaFormat, stream) do |ff|
				ff.each do |entry|
					name = entry.entry_id
					arr = entry.entry_id.split(".")
					g = Gene.new
					g.gene_set = gene_set
					g.name = name
					g.transcript = name
					g.cdna = name
					g.gene = arr[0]
					g.save!
					i += 1
					puts "Loaded #{i} genes (#{g.transcript})" if i % 1000 == 0
				end
			end
		end
	end

	def load_de_novo_genes(gene_set, filename)
		puts "Loading genes"
		ActiveRecord::Base.transaction do
		gene_set = GeneSet.find_or_create_by(:name => :gene_set)

		Bio::FlatFile.open(Bio::FastaFormat, :filename) do |ff|
			ff.each do |entry|
				arr = entry.definition.split(/ description:"(.*?)" *| /)
				g = Gene.new
				g.gene_set = gene_set
				name = arr.shift
				g.name = name
				g.transcript = name
				g.cdna = name
				g.save!
				end
			end
		end
	end

	def load_gff_produced_gens(gene_sets, filename)
		puts "Loading gff produced genes"
		i = 0
		ActiveRecord::Base.transaction do
		gene_set = GeneSet.find_or_create_by(:name => args[:gene_set])
		puts gene_set.inspect
		Bio::FlatFile.open(Bio::FastaFormat, args[:filename]) do |ff|
			ff.each do |entry|
				arr = entry.definition.split(/\s|\t/)
				g = Gene.new
				g.gene_set = gene_set
				g.name = arr.shift
				fields = Hash.new
				arr.each do |e|
					f = e.split("=")
					fields[f[0]] = f[1]
				end
				g.transcript = g.name
				g.gene = fields["gene"]
				g.cdna = fields["biotype"]
				g.save!
				i += 1
				puts "Loaded #{i} genes (#{g.transcript})" if i % 1000 == 0
				end
			end
		end
		puts "Loaded #{i} genes"
	end
end

app/views/genes/_form.html.erb
<%= form_for(@gene) do |f| %>
  <% if @gene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gene.errors.count, "error") %> prohibited this gene from being saved:</h2>

      <ul>
      <% @gene.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cdna %><br>
    <%= f.text_field :cdna %>
  </div>
  <div class="field">
    <%= f.label :possition %><br>
    <%= f.text_field :possition %>
  </div>
  <div class="field">
    <%= f.label :gene %><br>
    <%= f.text_field :gene %>
  </div>
  <div class="field">
    <%= f.label :transcript %><br>
    <%= f.text_field :transcript %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genes/_share.html.erb
<div id="share_area">
  <button id="share" value="settings" name="settings">Share</button>
  <p class="share_message"></p> 
</div> 

<div id="share_popup">
    <button type="button" id="close-button" class="ui-dialog-titlebar-close">x</button>    
    <input type="text">
    <br>
    <br>
    <p class="share_message" id="share_message_popup">Click on the below button and paste the link for sharing</p>
    <br>
    <button id="copy_link">Copy to Clipboard</button>
</div>


<%# If this is a shared link removed the data from the session and reload it with shared settings %> 
<% if @settings %>  
  <%= javascript_tag do %>        

    sessionStorage.clear();    
    var allSharedSettings = JSON.parse(<%= @settings.to_json.html_safe %>);        

    for(var key in allSharedSettings){
      sessionStorage.setItem(key, allSharedSettings[key]);
    }
  
  <% end %>
<% end %>
    
<script>  
  $("#share").click(function() {                

      // Looping through each session and storing them in an object            
      var selectedFactorsSessionObj = {};
      for (var i=0; i<sessionStorage.length; i++){        
        selectedFactorsSessionObj[sessionStorage.key(i)] = sessionStorage.getItem(sessionStorage.key(i));        
      }

      // Stringify all settings to send over request
      var allSettings = JSON.stringify(selectedFactorsSessionObj);           
      

      // Determining the data to be sent in the ajax request based on the url parameters
      var sendData;
      var searchGeneName = $('#search_gene_name').html();      
      var compareGeneName = $('#compare_gene_name').html();            
            
      if(compareGeneName){        
        sendData = {settings: allSettings, compare: compareGeneName, gene: searchGeneName};
      } else{       
        sendData = {settings: allSettings, gene: searchGeneName};
      }      

      // POST request for sending session data to the backend to generate the sharable link
      $.ajax({
        type: "POST",
        url: "share",
        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));},
        dataType: "json",
        data: sendData,
        success: function(data){                              
          $("#share_popup input").val(data.value);                    
        },
        error: function(){
          alert ("There was an error while processing the data to generate the sharable link");
        }
      });    
      
      // Display the popup with the sharable link
      $("#share_popup").show("slow");
      
      // Copy the link to the clipboard and close the popup
      $("#copy_link").click(function(){
        $("#share_popup input").select();
        document.execCommand("Copy");
        $("#share_popup").hide("slow");
        $(".share_message").html("The link has been copied to your clipboard");
      });

      // Close the popup when clicked on the cross
      $("#close-button").click(function (){
        $("#share_popup").hide("fast");
      });
  });
</script>

app/views/genes/edit.html.erb
<h1>Editing Gene</h1>

<%= render 'form' %>

<%= link_to 'Show', @gene %> |
<%= link_to 'Back', genes_path %>

app/views/genes/heatmap.html.erb
<%= render :partial => "genes/share" %>

<strong>Genes:</strong> 
<span id="heatmap_gene_name">
<% @gene.name.each do |gene| %>
<%= gene %> |
<% end %>
</span>
<% if @gene.knetminer %>
  <%= link_to "KnetMiner", @gene.knetminer %>
<% end %>

<div id="bar_expression_viewer"> </div>

<script type="text/javascript">  

  //rescaling the bar chart after a 1.5 second delay
  var resizeTimer;
  $(window).on('resize', function(e){
    //Making sure that the reload doesnt happen if the window is resized within 1.5 seconds
    clearTimeout(resizeTimer);  
    resizeTimer = setTimeout(function(){

      var windowHeight = $(window).outerHeight();
      var navHeight = $('nav').outerHeight();
      var footerHeight = 55;
      var contentHeight = 0;
            
      contentHeight = windowHeight - (navHeight + footerHeight) - 90;

      eb.resizeChart(contentHeight);
    }, 1500);
  });


  var windowHeight = $(window).outerHeight();  
  var navHeight = $('nav').outerHeight();
  var footerHeight = 55;
  var contentHeight = 0;
    
  contentHeight = windowHeight - (navHeight + footerHeight) - 90;

  var container_div="bar_expression_viewer";
  var data_url = "<%=raw "#{request.base_url}/expression_values/genes.json?#{@args}"%>" ;
  console.log(data_url);
  var parentWidth = $("#bar_expression_viewer").parent().width();
  var eb;
  function loadHeatmap(){
    eb =  new biovisexpressionbar.ExpressionBar({
      target: container_div,
      data: data_url,
      renderProperty: 'tpm', 
      defaultLog2State: true,
      fontFamily: 'Helvetica', 
      height: contentHeight,
      groupBy: ["High level stress-disease", "High level age","High level tissue","High level variety"],             
      width: parentWidth,
      plot:'HeatMap'
    });
    uncheckLog2();
  }     

  function uncheckLog2(){
    setTimeout(function(){                  
      if(sessionStorage.bar_expression_viewer_calculateLog == "false" && $("#bar_expression_viewer_log2").prop('checked', true)){
        $("#bar_expression_viewer_log2").click();
      }              
    }, 3000);
  }

  loadHeatmap();  
 
</script>

app/views/genes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Genes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cdna</th>
      <th>Possition</th>
      <th>Gene</th>
      <th>Transcript</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genes.each do |gene| %>
      <tr>
        <td><%= gene.name %></td>
        <td><%= gene.cdna %></td>
        <td><%= gene.possition %></td>
        <td><%= gene.gene %></td>
        <td><%= gene.transcript %></td>
        <td><%= link_to 'Show', gene %></td>
        <td><%= link_to 'Edit', edit_gene_path(gene) %></td>
        <td><%= link_to 'Destroy', gene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gene', new_gene_path %>

app/views/genes/new.html.erb
<h1>New Gene</h1>

<%= render 'form' %>

<%= link_to 'Back', genes_path %>

app/views/genes/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => "genes/share" %>

<strong><%= @gene.search_by%>:</strong> <span id="search_gene_name"><%= @gene.name %></span> 
<%= link_to "Ensembl", @gene.ensembl %>
<%= link_to "KnetMiner", @gene.knetminer %>

 
<% if @compare.name != "" %>
 <strong>Compare:</strong>
 <span id="compare_gene_name"><%= @compare.name %></span>   
 <%= link_to "Ensembl", @compare.ensembl %>
 <%= link_to "KnetMiner", @compare.knetminer %>
<% end %>

<div id="bar_expression_viewer"> </div>

<script type="text/javascript">

  // rescaling the bar chart after a 1.5 second delay
  var resizeTimer;
  $(window).on('resize', function(e){      
    clearTimeout(resizeTimer);  // Making sure that the reload doesnt happen if the window is resized within 1.5 seconds
    resizeTimer = setTimeout(function(){     

      var windowHeight = $(window).outerHeight();  
      var navHeight = $('nav').outerHeight();
      var footerHeight = 55;
      var contentHeight = 0;
            
      contentHeight = windowHeight - (navHeight + footerHeight) - 90;
     
      eb.resizeChart(contentHeight);
    }, 1500);
  });


  var windowHeight = $(window).outerHeight();  
  var navHeight = $('nav').outerHeight();
  var footerHeight = 55;
  var contentHeight = 0;
    
  contentHeight = windowHeight - (navHeight + footerHeight) - 90;

  var container_div="bar_expression_viewer";
  var data_url = "<%= "#{request.base_url}/expression_values/#{@gene.search_by}.json?#{@args}" %>" ;
  var gene = "<%= @gene.name %>";
  var eb;
  console.log(data_url);  
  console.log(window);
  function loadBarChart(){
    eb =  new ExpressionBar({
      target: container_div,
      highlight: gene, 
      data: data_url,
      height: contentHeight, 
      renderProperty: 'tpm', 
      fontFamily:'Helvetica', 
      groupBy: ["High level stress-disease", "High level age","High level tissue","High level variety"],                   
    });

  }
  loadBarChart();       
  //$("#bar_expression_viewer_sort_div").disableSelection(); //We need to move this to the js componen    
</script>